# Generated by Django 5.1.7 on 2025-03-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
