# Generated by Django 5.1.7 on 2025-03-15 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='address',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='details',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='details',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='details',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='pro',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='Otp',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
